/**
 * Data for the justification-comparison demo. Original typography-themed
 * prose (not copied from the pretext original), on the same subject —
 * typographic rivers and greedy vs. optimal line breaking — so the three
 * columns have realistic long-form English to justify. Hyphenation uses a
 * small exception dictionary for the longer words here plus generic English
 * prefix/suffix fallbacks; the dictionary only decides where a word MAY
 * break, so partial coverage degrades gracefully.
 */

export const PARAGRAPHS: readonly string[] = [
  "When a paragraph is justified, the browser stretches the spaces between words until each line reaches the column edge. On a narrow measure that stretching can grow large enough to open pale vertical channels of empty space that wander down through the block. Typographers call these channels rivers, and a trained eye reads them as a defect: the gaze snags on the gaps instead of gliding smoothly across each line.",
  "Careful compositors have fought rivers for centuries. They broke long words at syllable boundaries so a line could borrow a few letters from the next one, they nudged the spacing between individual characters, and above all they considered the paragraph as a whole rather than one line at a time. A break that looks fine on its own line can force an ugly gap two lines later, so the best spacing is only visible when every line is weighed together.",
  "The Knuth-Plass algorithm, written for the TeX typesetting system in 1981, turned that whole-paragraph instinct into mathematics. Instead of filling each line greedily, it treats every legal breakpoint as a node in a graph and searches for the sequence of breaks whose total spacing badness is smallest. Even a compact version of that idea, run over a few candidate breaks per line, produces noticeably calmer spacing than the line-by-line method browsers still use today.",
  "Ordinary CSS justification stays strictly greedy. The browser packs each line with as many words as will fit, then shares whatever room is left equally among the spaces, never looking ahead to the lines that follow. It is fast and needs no planning, but in a tight column one stubborn long word can blow a single line wide open, and the rivers that pour down from it are exactly the ones a metal-type compositor would have quietly closed by hand.",
] as const;

export const FONT_FAMILY = 'Georgia, "Times New Roman", serif';
export const FONT_SIZE = 15;
export const LINE_HEIGHT = 24;
export const FONT = `${FONT_SIZE}px ${FONT_FAMILY}`;
export const PAD = 14;
export const PARA_GAP = LINE_HEIGHT * 0.6;

/**
 * Explicit syllable breakdowns for the longer words in PARAGRAPHS, so the
 * hyphenated/optimal columns have realistic break opportunities. Keys are
 * lowercased and punctuation-stripped.
 */
export const HYPHEN_EXCEPTIONS: Record<string, readonly string[]> = {
  paragraph: ["par", "a", "graph"],
  justified: ["jus", "ti", "fied"],
  justification: ["jus", "ti", "fi", "ca", "tion"],
  browser: ["brows", "er"],
  browsers: ["brows", "ers"],
  stretching: ["stretch", "ing"],
  between: ["be", "tween"],
  vertical: ["ver", "ti", "cal"],
  vertically: ["ver", "ti", "cal", "ly"],
  channels: ["chan", "nels"],
  wander: ["wan", "der"],
  typographers: ["ty", "pog", "ra", "phers"],
  typesetting: ["type", "set", "ting"],
  defect: ["de", "fect"],
  smoothly: ["smooth", "ly"],
  compositor: ["com", "pos", "i", "tor"],
  compositors: ["com", "pos", "i", "tors"],
  centuries: ["cen", "tu", "ries"],
  syllable: ["syl", "la", "ble"],
  boundaries: ["bound", "a", "ries"],
  characters: ["char", "ac", "ters"],
  individual: ["in", "di", "vid", "u", "al"],
  considered: ["con", "sid", "ered"],
  spacing: ["spac", "ing"],
  algorithm: ["al", "go", "rithm"],
  typesetting2: ["type", "set", "ting"],
  mathematics: ["math", "e", "mat", "ics"],
  greedily: ["greed", "i", "ly"],
  breakpoint: ["break", "point"],
  breakpoints: ["break", "points"],
  sequence: ["se", "quence"],
  smallest: ["small", "est"],
  candidate: ["can", "di", "date"],
  produces: ["pro", "duces"],
  noticeably: ["no", "tice", "ably"],
  ordinary: ["or", "di", "nary"],
  strictly: ["strict", "ly"],
  whatever: ["what", "ever"],
  equally: ["e", "qual", "ly"],
  looking: ["look", "ing"],
  planning: ["plan", "ning"],
  stubborn: ["stub", "born"],
  quietly: ["qui", "et", "ly"],
  measure: ["meas", "ure"],
  smoothly2: ["smooth", "ly"],
  reaches: ["reach", "es"],
  reading: ["read", "ing"],
  instead: ["in", "stead"],
  gliding: ["glid", "ing"],
  borrow: ["bor", "row"],
  letters: ["let", "ters"],
  visible: ["vis", "i", "ble"],
  together: ["to", "geth", "er"],
  written: ["writ", "ten"],
  system: ["sys", "tem"],
  treats: ["treats"],
  searches: ["search", "es"],
  badness: ["bad", "ness"],
  compact: ["com", "pact"],
  calmer: ["calm", "er"],
  method: ["meth", "od"],
  packs: ["packs"],
  follow: ["fol", "low"],
  column: ["col", "umn"],
};

export const PREFIXES: readonly string[] = [
  "anti",
  "auto",
  "be",
  "bi",
  "co",
  "com",
  "con",
  "contra",
  "counter",
  "de",
  "dis",
  "en",
  "em",
  "ex",
  "extra",
  "fore",
  "hyper",
  "il",
  "im",
  "in",
  "inter",
  "intra",
  "ir",
  "macro",
  "mal",
  "micro",
  "mid",
  "mis",
  "mono",
  "multi",
  "non",
  "omni",
  "out",
  "over",
  "para",
  "poly",
  "post",
  "pre",
  "pro",
  "pseudo",
  "quasi",
  "re",
  "retro",
  "semi",
  "sub",
  "super",
  "sur",
  "syn",
  "tele",
  "trans",
  "tri",
  "ultra",
  "un",
  "under",
] as const;

export const SUFFIXES: readonly string[] = [
  "able",
  "ible",
  "tion",
  "sion",
  "ment",
  "ness",
  "ous",
  "ious",
  "eous",
  "ful",
  "less",
  "ive",
  "ative",
  "itive",
  "al",
  "ial",
  "ical",
  "ing",
  "ling",
  "ed",
  "er",
  "est",
  "ism",
  "ist",
  "ity",
  "ety",
  "ty",
  "ence",
  "ance",
  "ly",
  "fy",
  "ify",
  "ize",
  "ise",
  "ure",
  "ture",
] as const;
